version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: Project_3A
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
